# main.py
import json
from agents.state import AgentState
from agents.supervisor import supervisor_planner

def main():
    initial_state: AgentState = {
        "task": (
            "Perform market research on top vector databases in 2026, "
            "benchmark their latency via Python code, and write an executive summary."
        ),
        "plan": None,
        "completed_subtasks": [],
        "current_subtask_id": None,
        "current_specialist_output": None,
        "reviewer_verdict": None,
        "reviewer_feedback": None,
        "final_output": None,
        "error_count": 0,
        "human_approved": False,
    }

    print("Executing Supervisor Task Decomposition Node...")
    state_updates = supervisor_planner(initial_state)

    print("\n--- Plan Generated by Supervisor ---")
    print(json.dumps(state_updates["plan"], indent=2))
    print(f"\nNext Task To Execute: {state_updates['current_subtask_id']}")

if __name__ == "__main__":
    main()